<a href="https://colab.research.google.com/github/Pulkit4761/Pytorch/blob/main/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
#Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
#Subtraction longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
#Multiplication longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
#Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
#Division longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
#Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
#Modulus longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
#Exponents
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [ ]:
#Exponents longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])